
x-spark-common:
  &spark-common

  build: spark/
  environment:
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

services:
    spark-master:
        <<: *spark-common
        environment:
            - SPARK_MODE=master
        ports:
            - "8081:8080"
            - "7077:7077"

    spark-worker:
        <<: *spark-common
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark-master:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
        depends_on:
            - spark-master
